#include "stdafx.h"
#include "KeyTable.h"

const char* keyTable[] = {
    "",
    "Left mouse button",
    "Right mouse button",
    "Control-break processing",
    "Middle mouse button (three-button mouse)",
    "X1 mouse button",
    "X2 mouse button",
    "Undefined",
    "BACKSPACE",
    "TAB",
    "Reserved",
    "Reserved",
    "CLEAR",
    "ENTER",
    "Undefined",
    "Undefined",
    "SHIFT",
    "CTRL",
    "ALT",
    "PAUSE",
    "CAPS LOCK",
    "IME Kana mode / IME Hanguel mode (maintained for compatibility; use VK_HANGUL) / IME Hangul mode",
    "Undefined",
    "IME Junja mode",
    "IME final mode",
    "IME Hanja mode / IME Kanji mode",
    "Undefined",
    "ESC",
    "IME convert",
    "IME nonconvert",
    "IME accept",
    "IME mode change request",
    "SPACEBAR",
    "PAGE UP",
    "PAGE DOWN",
    "END",
    "HOME",
    "LEFT ARROW",
    "UP ARROW",
    "RIGHT ARROW",
    "DOWN ARROW",
    "SELECT",
    "PRINT",
    "EXECUTE",
    "PRINT SCREEN",
    "INS",
    "DEL",
    "HELP",
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "Undefined",
    "Undefined",
    "Undefined",
    "Undefined",
    "Undefined",
    "Undefined",
    "Undefined",
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "H",
    "I",
    "J",
    "K",
    "L",
    "M",
    "N",
    "O",
    "P",
    "Q",
    "R",
    "S",
    "T",
    "U",
    "V",
    "W",
    "X",
    "Y",
    "Z",
    "Left Windows",
    "Right Windows",
    "Applications",
    "Reserved",
    "Computer Sleep",
    "Numeric keypad 0",
    "Numeric keypad 1",
    "Numeric keypad 2",
    "Numeric keypad 3",
    "Numeric keypad 4",
    "Numeric keypad 5",
    "Numeric keypad 6",
    "Numeric keypad 7",
    "Numeric keypad 8",
    "Numeric keypad 9",
    "Multiply",
    "Add",
    "Separator",
    "Subtract",
    "Decimal",
    "Divide",
    "F1",
    "F2",
    "F3",
    "F4",
    "F5",
    "F6",
    "F7",
    "F8",
    "F9",
    "F10",
    "F11",
    "F12",
    "F13",
    "F14",
    "F15",
    "F16",
    "F17",
    "F18",
    "F19",
    "F20",
    "F21",
    "F22",
    "F23",
    "F24",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "NUM LOCK",
    "SCROLL LOCK",
    "OEM specific",
    "OEM specific",
    "OEM specific",
    "OEM specific",
    "OEM specific",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Left SHIFT",
    "Right SHIFT",
    "Left CONTROL",
    "Right CONTROL",
    "Left MENU",
    "Right MENU",
    "Browser Back",
    "Browser Forward",
    "Browser Refresh",
    "Browser Stop",
    "Browser Search",
    "Browser Favorites",
    "Browser Start and Home",
    "Volume Mute",
    "Volume Down",
    "Volume Up",
    "Next Track",
    "Previous Track",
    "Stop Media",
    "Play/Pause Media",
    "Start Mail",
    "Select Media",
    "Start Application 1",
    "Start Application 2",
    "Reserved",
    "Reserved",
    "Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard, the ';:'",
    "For any country/region, the '+'",
    "For any country/region, the ','",
    "For any country/region, the '-'",
    "For any country/region, the '.'",
    "Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard, the '/?'",
    "Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard, the '`~'",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Reserved",
    "Unassigned",
    "Unassigned",
    "Unassigned",
    "Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard, the '[{'",
    "Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard, the '\\|'",
    "Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard, the ']}'",
    "Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard, the 'single-quote/double-quote'",
    "Used for miscellaneous characters; it can vary by keyboard.",
    "Reserved",
    "OEM specific",
    "Either the angle bracket key or the backslash key on the RT 102-key keyboard",
    "OEM specific",
    "OEM specific",
    "IME PROCESS",
    "OEM specific",
    "Used to pass Unicode characters as if they were keystrokes. The VK_PACKET key is the low word of a 32-bit Virtual Key value used for non-keyboard input methods. For more information, see Remark in KEYBDINPUT, SendInput, WM_KEYDOWN, and WM_KEYUP",
    "Unassigned",
    "OEM specific",
    "OEM specific",
    "OEM specific",
    "OEM specific",
    "OEM specific",
    "OEM specific",
    "OEM specific",
    "OEM specific",
    "OEM specific",
    "OEM specific",
    "OEM specific",
    "OEM specific",
    "OEM specific",
    "Attn",
    "CrSel",
    "ExSel",
    "Erase EOF",
    "Play",
    "Zoom",
    "Reserved",
    "PA1",
    "Clear",
};
